# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clawkit < Formula
  desc "Unified CLI for OpenClaw, PicoClaw, ZeroClaw"
  homepage "https://github.com/huynextlevel/clawkit"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/huynextlevel/clawkit/releases/download/v0.2.0/clawkit_0.2.0_darwin_amd64.tar.gz"
      sha256 "f077fd94a6c287ee311b5c8a3dcb34421b6579f0b4989e991fba552080a6b0d6"

      def install
        bin.install "clawkit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/huynextlevel/clawkit/releases/download/v0.2.0/clawkit_0.2.0_darwin_arm64.tar.gz"
      sha256 "7dfc4ab89ea32cc62324b1e4ff110008b58361b635ffa6128745479439309c87"

      def install
        bin.install "clawkit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/huynextlevel/clawkit/releases/download/v0.2.0/clawkit_0.2.0_linux_amd64.tar.gz"
      sha256 "5f2eaef93f7c03ac8b602732753f3ef1c1805cf8413e6f54d9d7bc94792c7477"
      def install
        bin.install "clawkit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/huynextlevel/clawkit/releases/download/v0.2.0/clawkit_0.2.0_linux_arm64.tar.gz"
      sha256 "af69694599577fe687d602fe02ed342c05640e8e06d0624b8a0affe8b7c38a2d"
      def install
        bin.install "clawkit"
      end
    end
  end

  test do
    system "#{bin}/clawkit", "version"
  end
end
