# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clawkit < Formula
  desc "Unified CLI for OpenClaw, PicoClaw, ZeroClaw"
  homepage "https://github.com/huynextlevel/clawkit"
  version "0.2.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/huynextlevel/clawkit/releases/download/v0.2.8/clawkit_0.2.8_darwin_amd64.tar.gz"
      sha256 "44dffe4f12f1822e09e65b489b711d3a34e70a6add6a04b687ae9e0449c05bda"

      def install
        bin.install "clawkit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/huynextlevel/clawkit/releases/download/v0.2.8/clawkit_0.2.8_darwin_arm64.tar.gz"
      sha256 "736ee8021131e48792f5d90814b213c93919adfae8928717d27cf305f0635965"

      def install
        bin.install "clawkit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/huynextlevel/clawkit/releases/download/v0.2.8/clawkit_0.2.8_linux_amd64.tar.gz"
      sha256 "2413cb87a143960ad3342ab66cde46e693d75e94cc0ed2a7f5302d7d5b2e91bb"
      def install
        bin.install "clawkit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/huynextlevel/clawkit/releases/download/v0.2.8/clawkit_0.2.8_linux_arm64.tar.gz"
      sha256 "7a7dd350c841631f256e4ecd1231dba6eaacdabe0c8ebe7af1e8aeeaf7fe2d39"
      def install
        bin.install "clawkit"
      end
    end
  end

  test do
    system "#{bin}/clawkit", "version"
  end
end
